language: elixir
elixir:
  - 1.10.2
otp_release:
  - 22.2.8
sudo: false
env:
  - MIX_ENV=test
script: mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
